format = """
$directory\
$git_branch\
$git_status\
${custom.colima}\
$time\
\n$character"""

[git_branch]
symbol = ""
format = '[$symbol $branch ]($style)'

[git_status]
format = '[(\[$conflicted$deleted$renamed$modified$staged$untracked\])($ahead_behind)($stashed)]($style) '
conflicted = '[C${count}](bright-red)'
stashed = '[📦${count}](blue)'
deleted = '[D${count}](red)'
renamed = '[R${count}](bright-black)'
modified = '[M${count}](blue)'
staged = '[A${count}](green)'
untracked = '[U${count}](green)'
up_to_date = '✅'

[git_metrics]
disabled = true

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[ $time ]($style)'

[custom.colima]
command = 'if test -S ~/.colima/default/docker.sock; then echo 🐳; else echo 🌊; fi'
when = true
format = '[$output]($style) '

[aws]
disabled = true
